sudo: false
language: ruby
cache: bundler
rvm:
- 2.2.5

install:
  - bundle install
  - bundle exec jekyll build
  - find _site -type f -name "*.html" | while read f; do cp "$f" "${f%.html}"; done

deploy:
  provider: s3
  bucket: "nmcginn.com"
  skip_cleanup: true
  local_dir: _site

