# Jykell configuration
#markdown: redcarpet
#highlighter: pygments
markdown: kramdown
highlighter: rouge
paginate: 5
language: 'en-us'

# Website info
name: 'nmcginn.com'
description: "clever tagline here"

# Author's info
author: 'Nathan McGinn'
# edit 'categories' in the front matter of every post to match this username
nickname: Nathan
bio: 'A software developer, currently working in data science.'
location: 'St. Louis'
url: 'https://nmcginn.com'
image: 'assets/images/casper.png'

short_url: 'nmcginn.com/'
google_analytics: UA-55171430-2
baseurl: /

# Permalinks
permalink: /:title
# permalink: /author/:username
# permalink: /tag/:tag


# gems and other configs
gems: [jekyll-paginate]
exclude: [vendor]

# Additional settings available on the front-matter
# Site logo in the index.html (as in demo.ghost.io)
# Author's page cover in _layouts/author.html
# The same for page.html and tag.html layouts
# Post's page cover as a per-post basis _posts/...
# Disqus comments as a per-post basis
# ...


# Settings for builing master branch with travis-ci
# with jekyll-travis

# Settings for deploy rake task
# Username and repo of Github repo, e.g.
# https://github.com/USERNAME/REPO.git
# username defaults to ENV['GIT_NAME'] used by Travis
# repo defaults to USERNAME.github.io
# Branch defaults to "source" for USERNAME.github.io
# or "master" otherwise
safe: false
lsi: false
username: nmcginn
repo: blog
branch: master
relative_source: ../blog/
destination: _site/
production_url:  https://nmcginn.com/
source_url:      https://github.com/nmcginn/blog

exclude:
  - README.md
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - changelog.md
  - "*.Rmd"
  - vendor
  - .travis.yml
